name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    tags:
      - v1.0.0

  pull_request:

env:
  IMAGE_NAME: image

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
